<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbsenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'user_id' => 1,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 2,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 3,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 4,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 1,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 2,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 3,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'user_id' => 4,
                'periode_id' => 2,
                't_1' => 'OFF',
                't_2' => 'OFF',
                't_3' => 'H',
                't_4' => 'H',
                't_5' => 'H',
                't_6' => 'H',
                't_7' => 'OFF',
                't_8' => 'OFF',
                't_9' => 'H',
                't_10' => 'H',
                't_11' => 'H',
                't_12' => 'H',
                't_13' => 'OFF',
                't_14' => 'OFF',
                't_15' => 'H',
                't_16' => 'H',
                't_17' => 'H',
                't_18' => 'H',
                't_19' => 'OFF',
                't_20' => 'OFF',
                't_21' => 'H',
                't_22' => 'H',
                't_23' => 'H',
                't_24' => 'H',
                't_25' => 'OFF',
                't_26' => 'OFF',
                't_27' => 'H',
                't_28' => 'H',
                't_29' => 'H',
                't_30' => 'H',
                't_31' => 'OFF',
                'created_at' => now(),
                'updated_at' => null,
            ],
        ];
        DB::table('absen')->insert($data);
    }
}
